/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GoldKiwi Auth API
 * 인증 API 문서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  IssueTokenDto,
  LoginDto,
  RefreshTokenDto,
  SignupDto
} from './model';

/** Orval이 void 응답용으로 참조하지만 생성하지 않는 타입 */
type voidSuccess = Record<string, unknown>;

export const getAppControllerGetHelloUrl = () => {


  

  return `/api/`
}

export const appControllerGetHello = async ( options?: RequestInit): Promise<voidSuccess> => {
  
  const res = await fetch(getAppControllerGetHelloUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    
    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: voidSuccess = body ? JSON.parse(body) : {}
  return data
}





export const getAppControllerGetHelloQueryKey = () => {
    return [
    `/api/`
    ] as const;
    }

    
export const getAppControllerGetHelloQueryOptions = <TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppControllerGetHelloQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appControllerGetHello>>> = ({ signal }) => appControllerGetHello({ signal, ...fetchOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData> & { queryKey: DataTag<QueryKey, TData> }
}

export type AppControllerGetHelloQueryResult = NonNullable<Awaited<ReturnType<typeof appControllerGetHello>>>
export type AppControllerGetHelloQueryError = unknown


export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof appControllerGetHello>>,
          TError,
          Awaited<ReturnType<typeof appControllerGetHello>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }
export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> }

export function useAppControllerGetHello<TData = Awaited<ReturnType<typeof appControllerGetHello>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof appControllerGetHello>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {

  const queryOptions = getAppControllerGetHelloQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * 새로운 사용자를 등록합니다. username과 email은 고유해야 합니다.
 * @summary 회원 가입
 */
export const getAuthControllerSignupUrl = () => {


  

  return `/api/auth/signup`
}

export const authControllerSignup = async (signupDto: SignupDto, options?: RequestInit): Promise<voidSuccess> => {
  
  const res = await fetch(getAuthControllerSignupUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signupDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    
    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: voidSuccess = body ? JSON.parse(body) : {}
  return data
}




export const getAuthControllerSignupMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSignup>>, TError,{data: SignupDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerSignup>>, TError,{data: SignupDto}, TContext> => {

const mutationKey = ['authControllerSignup'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerSignup>>, {data: SignupDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerSignup(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerSignupMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerSignup>>>
    export type AuthControllerSignupMutationBody = SignupDto
    export type AuthControllerSignupMutationError = unknown

    /**
 * @summary 회원 가입
 */
export const useAuthControllerSignup = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerSignup>>, TError,{data: SignupDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerSignup>>,
        TError,
        {data: SignupDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerSignupMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * email 또는 username과 password로 인증 후 액세스/리프레시 토큰 발급. clientId/clientSecret 검증 필요. 토큰은 쿠키에 자동 설정됩니다.
 * @summary 로그인
 */
export const getAuthControllerLoginUrl = () => {


  

  return `/api/auth/login`
}

export const authControllerLogin = async (loginDto: LoginDto, options?: RequestInit): Promise<voidSuccess> => {
  
  const res = await fetch(getAuthControllerLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    
    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: voidSuccess = body ? JSON.parse(body) : {}
  return data
}




export const getAuthControllerLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['authControllerLogin'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLogin(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    export type AuthControllerLoginMutationBody = LoginDto
    export type AuthControllerLoginMutationError = unknown

    /**
 * @summary 로그인
 */
export const useAuthControllerLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        {data: LoginDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerLoginMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * clientId/clientSecret 검증 후 userId로 사용자 조회하여 액세스/리프레시 토큰 발급 (쿠키·클라이언트 검증용)
 * @summary 토큰 발급
 */
export const getAuthControllerIssueTokenUrl = () => {


  

  return `/api/auth/token`
}

export const authControllerIssueToken = async (issueTokenDto: IssueTokenDto, options?: RequestInit): Promise<voidSuccess> => {
  
  const res = await fetch(getAuthControllerIssueTokenUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      issueTokenDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    
    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: voidSuccess = body ? JSON.parse(body) : {}
  return data
}




export const getAuthControllerIssueTokenMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerIssueToken>>, TError,{data: IssueTokenDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerIssueToken>>, TError,{data: IssueTokenDto}, TContext> => {

const mutationKey = ['authControllerIssueToken'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerIssueToken>>, {data: IssueTokenDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerIssueToken(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerIssueTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerIssueToken>>>
    export type AuthControllerIssueTokenMutationBody = IssueTokenDto
    export type AuthControllerIssueTokenMutationError = unknown

    /**
 * @summary 토큰 발급
 */
export const useAuthControllerIssueToken = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerIssueToken>>, TError,{data: IssueTokenDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerIssueToken>>,
        TError,
        {data: IssueTokenDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerIssueTokenMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 리프레시 토큰: body 또는 쿠키(refreshToken). clientId/clientSecret 검증 후 새 쌍 발급.
 * @summary 토큰 갱신
 */
export const getAuthControllerRefreshUrl = () => {


  

  return `/api/auth/refresh`
}

export const authControllerRefresh = async (refreshTokenDto: RefreshTokenDto, options?: RequestInit): Promise<voidSuccess> => {
  
  const res = await fetch(getAuthControllerRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshTokenDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    
    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: voidSuccess = body ? JSON.parse(body) : {}
  return data
}




export const getAuthControllerRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,{data: RefreshTokenDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,{data: RefreshTokenDto}, TContext> => {

const mutationKey = ['authControllerRefresh'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefresh>>, {data: RefreshTokenDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerRefresh(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefresh>>>
    export type AuthControllerRefreshMutationBody = RefreshTokenDto
    export type AuthControllerRefreshMutationError = unknown

    /**
 * @summary 토큰 갱신
 */
export const useAuthControllerRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefresh>>, TError,{data: RefreshTokenDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRefresh>>,
        TError,
        {data: RefreshTokenDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerRefreshMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * 리프레시 토큰: body 또는 쿠키(refreshToken). clientId/clientSecret 검증 후 무효화.
 * @summary 리프레시 토큰 무효화
 */
export const getAuthControllerRevokeUrl = () => {


  

  return `/api/auth/revoke`
}

export const authControllerRevoke = async (refreshTokenDto: RefreshTokenDto, options?: RequestInit): Promise<voidSuccess> => {
  
  const res = await fetch(getAuthControllerRevokeUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshTokenDto,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    
    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: voidSuccess = body ? JSON.parse(body) : {}
  return data
}




export const getAuthControllerRevokeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRevoke>>, TError,{data: RefreshTokenDto}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRevoke>>, TError,{data: RefreshTokenDto}, TContext> => {

const mutationKey = ['authControllerRevoke'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRevoke>>, {data: RefreshTokenDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerRevoke(data,fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRevokeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRevoke>>>
    export type AuthControllerRevokeMutationBody = RefreshTokenDto
    export type AuthControllerRevokeMutationError = unknown

    /**
 * @summary 리프레시 토큰 무효화
 */
export const useAuthControllerRevoke = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRevoke>>, TError,{data: RefreshTokenDto}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRevoke>>,
        TError,
        {data: RefreshTokenDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerRevokeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }

/**
 * 리프레시 토큰 무효화 후 accessToken/refreshToken 쿠키 삭제. clientId/clientSecret 필요.
 * @summary 로그아웃
 */
export const getAuthControllerLogoutUrl = () => `/api/auth/logout`;

export const authControllerLogout = async (
  refreshTokenDto: RefreshTokenDto,
  options?: RequestInit,
): Promise<{ ok: boolean }> => {
  const res = await fetch(getAuthControllerLogoutUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(refreshTokenDto),
  });
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    const err: Error & { info?: unknown; status?: number } = new Error();
    err.info = body ? JSON.parse(body) : {};
    err.status = res.status;
    throw err;
  }
  return body ? JSON.parse(body) : { ok: true };
};

export const getAuthControllerLogoutMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogout>>,
      TError,
      { data: RefreshTokenDto },
      TContext
    >;
    fetch?: RequestInit;
  },
) => {
  const mutationKey = ["authControllerLogout"];
  const { mutation: mutationOptions, fetch: fetchOptions } = options ?? {};
  const mergedMutation =
    mutationOptions && "mutationKey" in mutationOptions
      ? mutationOptions
      : { ...mutationOptions, mutationKey };
  return {
    mutationKey,
    mutationFn: ({ data }: { data: RefreshTokenDto }) =>
      authControllerLogout(data, fetchOptions),
    ...mergedMutation,
  };
};

export const useAuthControllerLogout = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogout>>,
      TError,
      { data: RefreshTokenDto },
      TContext
    >;
    fetch?: RequestInit;
  },
  queryClient?: QueryClient,
) => useMutation(getAuthControllerLogoutMutationOptions(options), queryClient);

/**
 * 액세스 토큰: 쿠키(accessToken) 또는 Authorization Bearer. public.key로 검증 후 payload 반환.
 * @summary 현재 사용자
 */
export const getAuthControllerMeUrl = () => {


  

  return `/api/auth/me`
}

export const authControllerMe = async ( options?: RequestInit): Promise<voidSuccess> => {
  
  const res = await fetch(getAuthControllerMeUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  if (!res.ok) {
    
    const err: globalThis.Error & {info?: any, status?: number} = new globalThis.Error();
    const data  = body ? JSON.parse(body) : {}
    err.info = data;
    err.status = res.status;
    throw err;
  }
  const data: voidSuccess = body ? JSON.parse(body) : {}
  return data
}




export const getAuthControllerMeMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerMe>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerMe>>, TError,void, TContext> => {

const mutationKey = ['authControllerMe'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerMe>>, void> = () => {
          

          return  authControllerMe(fetchOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerMeMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerMe>>>
    
    export type AuthControllerMeMutationError = unknown

    /**
 * @summary 현재 사용자
 */
export const useAuthControllerMe = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerMe>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof authControllerMe>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerMeMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
