/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GoldKiwi Auth API
 * 인증 API 문서
 * OpenAPI spec version: 1.0
 */

export interface IssueTokenDto {
  /** 클라이언트 ID (Client.clientId) */
  clientId: string;
  /** 클라이언트 시크릿 (Client.clientSecret) */
  clientSecret: string;
  /** 토큰 발급 대상 사용자 ID */
  userId: string;
}
