/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GoldKiwi Auth API
 * 인증 API 문서
 * OpenAPI spec version: 1.0
 */

export interface LoginDto {
  /** 클라이언트 ID (Client.clientId) */
  clientId: string;
  /** 클라이언트 시크릿 (Client.clientSecret) */
  clientSecret: string;
  /** 이메일 (username이 없을 경우 필수) */
  email?: string;
  /** 사용자명 (email이 없을 경우 필수) */
  username?: string;
  /** 비밀번호 */
  password: string;
}
