/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GoldKiwi Auth API
 * 인증 API 문서
 * OpenAPI spec version: 1.0
 */

export interface RefreshTokenDto {
  /** 클라이언트 ID (Client.clientId) */
  clientId: string;
  /** 클라이언트 시크릿 (Client.clientSecret) */
  clientSecret: string;
  /** 리프레시 토큰. 없으면 쿠키 refreshToken 사용 (cookie-parser) */
  refreshToken?: string;
}
