/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * GoldKiwi Auth API
 * 인증 API 문서
 * OpenAPI spec version: 1.0
 */

export interface SignupDto {
  /** 사용자명 (고유) */
  username: string;
  /** 이메일 (고유) */
  email: string;
  /** 비밀번호 (최소 8자) */
  password: string;
  /** 이름 */
  name: string;
}
